/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WorksRouteImport } from './routes/works'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as ProfilesProfileIdRouteImport } from './routes/profiles.$profileId'
import { Route as AiLocationRouteImport } from './routes/ai.location'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesProfileIdRoute = ProfilesProfileIdRouteImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLocationRoute = AiLocationRouteImport.update({
  id: '/ai/location',
  path: '/ai/location',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contests': typeof ContestsRoute
  '/discover': typeof DiscoverRoute
  '/works': typeof WorksRoute
  '/workspace': typeof WorkspaceRoute
  '/ai/location': typeof AiLocationRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contests': typeof ContestsRoute
  '/discover': typeof DiscoverRoute
  '/works': typeof WorksRoute
  '/workspace': typeof WorkspaceRoute
  '/ai/location': typeof AiLocationRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contests': typeof ContestsRoute
  '/discover': typeof DiscoverRoute
  '/works': typeof WorksRoute
  '/workspace': typeof WorkspaceRoute
  '/ai/location': typeof AiLocationRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contests'
    | '/discover'
    | '/works'
    | '/workspace'
    | '/ai/location'
    | '/profiles/$profileId'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contests'
    | '/discover'
    | '/works'
    | '/workspace'
    | '/ai/location'
    | '/profiles/$profileId'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contests'
    | '/discover'
    | '/works'
    | '/workspace'
    | '/ai/location'
    | '/profiles/$profileId'
    | '/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContestsRoute: typeof ContestsRoute
  DiscoverRoute: typeof DiscoverRoute
  WorksRoute: typeof WorksRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AiLocationRoute: typeof AiLocationRoute
  ProfilesProfileIdRoute: typeof ProfilesProfileIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$profileId': {
      id: '/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof ProfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/location': {
      id: '/ai/location'
      path: '/ai/location'
      fullPath: '/ai/location'
      preLoaderRoute: typeof AiLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContestsRoute: ContestsRoute,
  DiscoverRoute: DiscoverRoute,
  WorksRoute: WorksRoute,
  WorkspaceRoute: WorkspaceRoute,
  AiLocationRoute: AiLocationRoute,
  ProfilesProfileIdRoute: ProfilesProfileIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
