SET NAMES utf8mb4;

INSERT INTO common_code_group (code_group, group_name, description) VALUES
('ACCOUNT_TYPE', '계정 유형', '사용자, 회사, 관리자'),
('ACCOUNT_STATUS', '계정 상태', '계정 활성, 승인 대기, 제재 상태'),
('COMPANY_APPLICATION_STATUS', '회사 승인 상태', '회사 계정 승인 흐름'),
('ADMIN_PERMISSION', '관리자 권한', '관리자 권한 코드'),
('PROFILE_VISIBILITY', '프로필 공개 범위', '프로필 공개 범위'),
('ACTIVITY_STATUS', '활동 여부', '매칭 후보 노출 상태'),
('EXPERIENCE_LEVEL', '경력 단계', '프로필과 모집 요구 경력'),
('JOIN_AVAILABILITY', '합류 가능 시점', '팀 합류 가능 시점'),
('COLLABORATION_STATUS', '협업 가능 상태', '현재 협업 가능성'),
('COLLABORATION_CONDITION', '협업 조건', '보상/수익 배분 조건'),
('TRAVEL_RANGE', '이동 가능 범위', '지역 거리 허용 범위'),
('DURATION', '작업 기간', '선호/예상 작업 기간'),
('EQUIPMENT_STATUS', '장비 보유 여부', '선택 표시 정보'),
('AGE_BAND', '연령대', '선택 표시 정보'),
('PARTICIPATION_MODE', '참여 방식', '선택 표시 정보'),
('TEAM_STATUS', '팀 상태', '팀 진행 상태'),
('TEAM_END_TYPE', '팀 종료 유형', '정상 종료 또는 해체'),
('TEAM_MEMBER_ROLE', '팀원 권한', '팀 내 권한'),
('TEAM_MEMBER_STATUS', '팀원 상태', '팀 참여 상태'),
('RECRUITMENT_STATUS', '모집 공고 상태', '모집 공고 상태'),
('SLOT_STATUS', '모집 슬롯 상태', '역할별 모집 상태'),
('REQUEST_STATUS', '요청 상태', '지원과 초대 상태'),
('PLAN_STATUS', '팀 계획 상태', '일정과 할 일 상태'),
('BOARD_CATEGORY', '게시판 카테고리', '작업물과 자유 게시판'),
('FREE_POST_CATEGORY', '자유게시판 세부 분류', '공지, 질문, 정보, 후기, 자유'),
('BOARD_STATUS', '게시글 상태', '게시글 노출 상태'),
('BOARD_VISIBILITY', '게시글 공개 범위', '게시글 공개 범위'),
('REPORT_TARGET_TYPE', '신고 대상 유형', '신고 가능한 콘텐츠 유형'),
('REPORT_REASON', '신고 사유', '게시글과 리뷰 신고 사유'),
('REPORT_STATUS', '신고 처리 상태', '콘텐츠 신고 검토 상태'),
('MODERATION_ACTION', '신고 처리 조치', '신고 승인 시 운영 조치'),
('SANCTION_TYPE', '사용자 제재 유형', '임시 정지와 영구 정지'),
('SANCTION_STATUS', '사용자 제재 상태', '사용자 제재 활성, 해제, 만료'),
('WORK_VISIBILITY', '작업물 공개 범위', '작업물 공개 범위'),
('WORK_TYPE', '작업물 종류', '작업물 형식 분류'),
('TEAM_WORK_APPROVAL_STATUS', '팀 작업물 승인 상태', '팀 작업물 업로드 승인 흐름'),
('CONTEST_TYPE', '공모전 유형', '자체 공모전과 외부 공모전'),
('CONTEST_STATUS', '공모전 상태', '공모전 진행 상태'),
('CONTEST_OPEN_REQUEST_STATUS', '공모전 개설 요청 상태', '회사 공모전 개설 요청 검토 상태'),
('NOTIFICATION_TYPE', '알림 유형', '내부 알림 유형');

INSERT INTO common_code (code_group, code, display_name, description, sort_order) VALUES
('ACCOUNT_TYPE', 'USER', '일반 사용자', NULL, 1),
('ACCOUNT_TYPE', 'COMPANY', '회사 사용자', NULL, 2),
('ACCOUNT_TYPE', 'ADMIN', '관리자', NULL, 3),
('ACCOUNT_STATUS', 'ACTIVE', '정상', NULL, 1),
('ACCOUNT_STATUS', 'PENDING_APPROVAL', '승인 대기', '회사 계정 승인 전 상태', 2),
('ACCOUNT_STATUS', 'TEMP_SUSPENDED', '임시 정지', NULL, 3),
('ACCOUNT_STATUS', 'PERM_SUSPENDED', '영구 정지', NULL, 4),
('ACCOUNT_STATUS', 'WITHDRAWN', '회원 탈퇴', NULL, 5),
('COMPANY_APPLICATION_STATUS', 'PENDING', '검토 대기', NULL, 1),
('COMPANY_APPLICATION_STATUS', 'APPROVED', '승인', NULL, 2),
('COMPANY_APPLICATION_STATUS', 'REJECTED', '거절', NULL, 3),
('ADMIN_PERMISSION', 'COMPANY_APPROVAL', '회사 승인', NULL, 1),
('ADMIN_PERMISSION', 'USER_SANCTION', '사용자 제재', NULL, 2),
('ADMIN_PERMISSION', 'CONTENT_MODERATION', '게시글/리뷰 관리', NULL, 3),
('ADMIN_PERMISSION', 'SCORE_POLICY', '점수 정책 관리', NULL, 4),
('ADMIN_PERMISSION', 'CONTEST_MANAGE', '공모전 관리', NULL, 5),
('ADMIN_PERMISSION', 'DEMO_ACCESS_MANAGE', '접근 코드 관리', NULL, 6),
('ADMIN_PERMISSION', 'NOTIFICATION_SEND', '알림 발송', NULL, 7),
('ADMIN_PERMISSION', 'LOG_VIEW', '로그 조회', NULL, 8),
('ADMIN_PERMISSION', 'ADMIN_PERMISSION_MANAGE', '관리자 권한 관리', NULL, 9),
('ADMIN_PERMISSION', 'REGION_MANAGE', '지역 DB 관리', NULL, 10),
('PROFILE_VISIBILITY', 'PUBLIC', '전체 공개', NULL, 1),
('PROFILE_VISIBILITY', 'COMPANY', '회사 공개', NULL, 2),
('PROFILE_VISIBILITY', 'PRIVATE', '비공개', NULL, 3),
('ACTIVITY_STATUS', 'VISIBLE', '매칭 노출', NULL, 1),
('ACTIVITY_STATUS', 'HIDDEN', '매칭 숨김', NULL, 2),
('EXPERIENCE_LEVEL', 'Y0_3', '0년~3년', NULL, 1),
('EXPERIENCE_LEVEL', 'Y3_10', '3년~10년', NULL, 2),
('EXPERIENCE_LEVEL', 'Y10_PLUS', '10년 이상', NULL, 3),
('JOIN_AVAILABILITY', 'IMMEDIATE', '즉시 가능', NULL, 1),
('JOIN_AVAILABILITY', 'WITHIN_1W', '1주 이내', NULL, 2),
('JOIN_AVAILABILITY', 'WITHIN_2W', '2주 이내', NULL, 3),
('JOIN_AVAILABILITY', 'WITHIN_1M', '1개월 이내', NULL, 4),
('JOIN_AVAILABILITY', 'AFTER_1M', '1개월 이후', NULL, 5),
('JOIN_AVAILABILITY', 'NEGOTIABLE', '일정 협의 가능', NULL, 6),
('COLLABORATION_STATUS', 'AVAILABLE', '협업 가능', NULL, 1),
('COLLABORATION_STATUS', 'CONSIDERING', '제안 검토 가능', NULL, 2),
('COLLABORATION_STATUS', 'UNAVAILABLE', '현재 불가', NULL, 3),
('COLLABORATION_CONDITION', 'UNPAID', '무급', NULL, 1),
('COLLABORATION_CONDITION', 'NEGOTIABLE', '협의 가능', NULL, 2),
('COLLABORATION_CONDITION', 'PAID', '유급', NULL, 3),
('COLLABORATION_CONDITION', 'REVENUE_SHARE', '수익 배분', NULL, 4),
('COLLABORATION_CONDITION', 'PRIZE_SHARE', '상금 배분', NULL, 5),
('COLLABORATION_CONDITION', 'ANY', '무관', NULL, 6),
('TRAVEL_RANGE', 'KM_10', '10km 이내', NULL, 1),
('TRAVEL_RANGE', 'KM_30', '30km 이내', NULL, 2),
('TRAVEL_RANGE', 'KM_100', '100km 이내', NULL, 3),
('TRAVEL_RANGE', 'ANYWHERE', '거리 무관', NULL, 4),
('DURATION', 'WITHIN_1M', '1개월 이하', NULL, 1),
('DURATION', 'WITHIN_3M', '3개월 이하', NULL, 2),
('DURATION', 'WITHIN_6M', '6개월 이하', NULL, 3),
('DURATION', 'ANY', '무관', NULL, 4),
('EQUIPMENT_STATUS', 'HAS_EQUIPMENT', '보유', NULL, 1),
('EQUIPMENT_STATUS', 'NO_EQUIPMENT', '미보유', NULL, 2),
('EQUIPMENT_STATUS', 'NOT_ENTERED', '미입력', NULL, 3),
('AGE_BAND', 'TEENS', '10대', NULL, 1),
('AGE_BAND', 'TWENTIES', '20대', NULL, 2),
('AGE_BAND', 'THIRTIES', '30대', NULL, 3),
('AGE_BAND', 'FORTIES', '40대', NULL, 4),
('AGE_BAND', 'FIFTY_PLUS', '50대 이상', NULL, 5),
('AGE_BAND', 'PRIVATE', '비공개', NULL, 6),
('PARTICIPATION_MODE', 'OFFLINE', '오프라인', NULL, 1),
('PARTICIPATION_MODE', 'REMOTE', '원격', NULL, 2),
('PARTICIPATION_MODE', 'HYBRID', '혼합', NULL, 3),
('TEAM_STATUS', 'RECRUITING', '모집 중', NULL, 1),
('TEAM_STATUS', 'IN_PROGRESS', '진행 중', NULL, 2),
('TEAM_STATUS', 'RECRUITMENT_CLOSED', '모집 완료', NULL, 3),
('TEAM_STATUS', 'CLOSING', '종료 예정', NULL, 4),
('TEAM_STATUS', 'ENDED', '종료', NULL, 5),
('TEAM_END_TYPE', 'NORMAL', '정상 종료', NULL, 1),
('TEAM_END_TYPE', 'DISSOLUTION', '해체', NULL, 2),
('TEAM_MEMBER_ROLE', 'LEADER', '팀장', NULL, 1),
('TEAM_MEMBER_ROLE', 'SUB_LEADER', '부팀장', NULL, 2),
('TEAM_MEMBER_ROLE', 'MEMBER', '팀원', NULL, 3),
('TEAM_MEMBER_STATUS', 'ACTIVE', '참여 중', NULL, 1),
('TEAM_MEMBER_STATUS', 'LEFT', '탈퇴', NULL, 2),
('TEAM_MEMBER_STATUS', 'KICKED', '강퇴', NULL, 3),
('RECRUITMENT_STATUS', 'OPEN', '모집 중', NULL, 1),
('RECRUITMENT_STATUS', 'CLOSED', '마감', NULL, 2),
('SLOT_STATUS', 'OPEN', '모집 중', NULL, 1),
('SLOT_STATUS', 'CLOSED', '마감', NULL, 2),
('REQUEST_STATUS', 'PENDING', '대기', NULL, 1),
('REQUEST_STATUS', 'ACCEPTED', '수락', NULL, 2),
('REQUEST_STATUS', 'REJECTED', '거절', NULL, 3),
('REQUEST_STATUS', 'CANCELED', '취소', NULL, 4),
('REQUEST_STATUS', 'EXPIRED', '만료', NULL, 5),
('PLAN_STATUS', 'TODO', '대기', NULL, 1),
('PLAN_STATUS', 'IN_PROGRESS', '진행 중', NULL, 2),
('PLAN_STATUS', 'DONE', '완료', NULL, 3),
('PLAN_STATUS', 'HOLD', '보류', NULL, 4),
('PLAN_STATUS', 'CANCELED', '취소', NULL, 5),
('BOARD_CATEGORY', 'WORK', '작업물', NULL, 1),
('BOARD_CATEGORY', 'FREE', '자유', NULL, 2),
('FREE_POST_CATEGORY', 'NOTICE', '공지', NULL, 1),
('FREE_POST_CATEGORY', 'QUESTION', '질문', NULL, 2),
('FREE_POST_CATEGORY', 'INFO', '정보', NULL, 3),
('FREE_POST_CATEGORY', 'REVIEW', '후기', NULL, 4),
('FREE_POST_CATEGORY', 'FREE', '자유', NULL, 5),
('BOARD_STATUS', 'PUBLISHED', '게시', NULL, 1),
('BOARD_STATUS', 'AUTHOR_DELETED', '작성자 삭제', NULL, 2),
('BOARD_STATUS', 'ADMIN_DELETED', '관리자 삭제', NULL, 3),
('BOARD_STATUS', 'BLINDED', '운영 숨김', NULL, 4),
('BOARD_VISIBILITY', 'PUBLIC', '전체 공개', NULL, 1),
('BOARD_VISIBILITY', 'COMPANY', '회사 공개', NULL, 2),
('REPORT_TARGET_TYPE', 'BOARD_POST', '게시글', NULL, 1),
('REPORT_TARGET_TYPE', 'BOARD_REVIEW', '리뷰', NULL, 2),
('REPORT_REASON', 'SPAM', '스팸/홍보', NULL, 1),
('REPORT_REASON', 'ABUSE', '욕설/비방', NULL, 2),
('REPORT_REASON', 'ILLEGAL', '불법/권리 침해', NULL, 3),
('REPORT_REASON', 'PRIVACY', '개인정보 노출', NULL, 4),
('REPORT_REASON', 'OTHER', '기타', NULL, 5),
('REPORT_STATUS', 'PENDING', '검토 대기', NULL, 1),
('REPORT_STATUS', 'ACCEPTED', '처리 완료', NULL, 2),
('REPORT_STATUS', 'REJECTED', '반려', NULL, 3),
('MODERATION_ACTION', 'NONE', '조치 없음', NULL, 1),
('MODERATION_ACTION', 'BLIND_POST', '게시글 숨김', NULL, 2),
('MODERATION_ACTION', 'DELETE_POST', '게시글 삭제', NULL, 3),
('MODERATION_ACTION', 'BLIND_REVIEW', '리뷰 숨김', NULL, 4),
('MODERATION_ACTION', 'DELETE_REVIEW', '리뷰 삭제', NULL, 5),
('SANCTION_TYPE', 'TEMP_SUSPENDED', '임시 정지', NULL, 1),
('SANCTION_TYPE', 'PERM_SUSPENDED', '영구 정지', NULL, 2),
('SANCTION_STATUS', 'ACTIVE', '활성', NULL, 1),
('SANCTION_STATUS', 'REVOKED', '해제', NULL, 2),
('SANCTION_STATUS', 'EXPIRED', '만료', NULL, 3),
('WORK_VISIBILITY', 'PUBLIC', '전체 공개', NULL, 1),
('WORK_VISIBILITY', 'COMPANY', '회사 공개', NULL, 2),
('WORK_TYPE', 'SHORT_FILM', '단편영화', NULL, 1),
('WORK_TYPE', 'FEATURE_FILM', '장편영화', NULL, 2),
('WORK_TYPE', 'MUSIC_VIDEO', '뮤직비디오', NULL, 3),
('WORK_TYPE', 'ADVERTISEMENT', '광고', NULL, 4),
('WORK_TYPE', 'DOCUMENTARY', '다큐멘터리', NULL, 5),
('WORK_TYPE', 'WEB_CONTENT', '웹 콘텐츠', NULL, 6),
('WORK_TYPE', 'OTHER', '기타', NULL, 7),
('TEAM_WORK_APPROVAL_STATUS', 'PENDING', '승인 대기', NULL, 1),
('TEAM_WORK_APPROVAL_STATUS', 'APPROVED', '승인', NULL, 2),
('TEAM_WORK_APPROVAL_STATUS', 'REJECTED', '거절', NULL, 3),
('TEAM_WORK_APPROVAL_STATUS', 'CANCELED', '취소', NULL, 4),
('CONTEST_TYPE', 'INTERNAL', '자체 공모전', NULL, 1),
('CONTEST_TYPE', 'EXTERNAL', '외부 공모전', NULL, 2),
('CONTEST_STATUS', 'OPEN', '진행 중', NULL, 1),
('CONTEST_STATUS', 'ENDED', '종료', NULL, 2),
('CONTEST_OPEN_REQUEST_STATUS', 'PENDING', '검토 대기', NULL, 1),
('CONTEST_OPEN_REQUEST_STATUS', 'APPROVED', '승인', NULL, 2),
('CONTEST_OPEN_REQUEST_STATUS', 'REJECTED', '거절', NULL, 3),
('NOTIFICATION_TYPE', 'SYSTEM', '시스템', NULL, 1),
('NOTIFICATION_TYPE', 'TEAM', '팀', NULL, 2),
('NOTIFICATION_TYPE', 'MATCHING', '매칭', NULL, 3),
('NOTIFICATION_TYPE', 'ADMIN', '관리자 발송', NULL, 4);

INSERT INTO region (region_code, sido_name, sigungu_name, dong_name, center_lat, center_lng, public_display_name) VALUES
('1111010100', '서울특별시', '종로구', '청운효자동', 37.5840090, 126.9706260, '서울특별시 종로구'),
('1114016200', '서울특별시', '중구', '명동', 37.5636560, 126.9850280, '서울특별시 중구'),
('1168010100', '서울특별시', '강남구', '역삼동', 37.5006130, 127.0364310, '서울특별시 강남구'),
('1144012000', '서울특별시', '마포구', '서교동', 37.5550200, 126.9224310, '서울특별시 마포구'),
('1121510100', '서울특별시', '광진구', '화양동', 37.5445810, 127.0708090, '서울특별시 광진구'),
('4113510800', '경기도', '성남시 분당구', '삼평동', 37.4000590, 127.1086220, '경기도 성남시 분당구'),
('4128112800', '경기도', '고양시 덕양구', '화정동', 37.6375710, 126.8326120, '경기도 고양시 덕양구'),
('2611014000', '부산광역시', '중구', '남포동', 35.0981850, 129.0325710, '부산광역시 중구'),
('2711015700', '대구광역시', '중구', '삼덕동', 35.8658440, 128.6085560, '대구광역시 중구'),
('2915510900', '광주광역시', '남구', '양림동', 35.1396990, 126.9120940, '광주광역시 남구'),
('3011014000', '대전광역시', '동구', '대동', 36.3293670, 127.4433150, '대전광역시 동구'),
('5011013700', '제주특별자치도', '제주시', '이도이동', 33.4996210, 126.5311880, '제주특별자치도 제주시');

INSERT INTO role_category (role_category_id, name, sort_order) VALUES
(1, '기획/제작', 1),
(2, '연출', 2),
(3, '각본', 3),
(4, '촬영', 4),
(5, '조명', 5),
(6, '음향', 6),
(7, '미술', 7),
(8, '분장/의상', 8),
(9, '배우', 9),
(10, '편집', 10),
(11, '후반/VFX', 11),
(12, '음악', 12),
(13, '홍보/배급', 13),
(14, '기타', 14);

INSERT INTO `role` (role_id, role_category_id, name, sort_order) VALUES
(1, 1, '프로듀서', 1),
(2, 1, '제작PD', 2),
(3, 1, '라인프로듀서', 3),
(4, 2, '감독', 1),
(5, 2, '조감독', 2),
(6, 2, '스크립터', 3),
(7, 3, '시나리오 작가', 1),
(8, 3, '구성 작가', 2),
(9, 4, '촬영감독', 1),
(10, 4, '카메라 오퍼레이터', 2),
(11, 4, '드론 촬영', 3),
(12, 5, '조명감독', 1),
(13, 5, '조명부', 2),
(14, 6, '동시녹음', 1),
(15, 6, '사운드 디자인', 2),
(16, 7, '미술감독', 1),
(17, 7, '소품', 2),
(18, 8, '분장', 1),
(19, 8, '의상', 2),
(20, 9, '배우', 1),
(21, 9, '성우/내레이션', 2),
(22, 10, '영상 편집', 1),
(23, 11, '색보정', 1),
(24, 11, 'VFX', 2),
(25, 12, '음악감독', 1),
(26, 13, '마케팅', 1),
(27, 13, '배급 매니저', 2),
(28, 14, '자문/멘토링', 1);

INSERT INTO genre (genre_id, name, description, sort_order) VALUES
(1, '드라마', '인물과 관계 중심 서사', 1),
(2, '로맨스', '사랑과 관계 중심', 2),
(3, '코미디', '유머와 풍자 중심', 3),
(4, '액션', '추격과 물리적 사건 중심', 4),
(5, '스릴러', '긴장감과 위협 중심', 5),
(6, '공포', '공포감과 괴담 중심', 6),
(7, '미스터리', '사건의 진실 추적', 7),
(8, '범죄', '범죄와 수사 중심', 8),
(9, 'SF', '과학기술과 미래 중심', 9),
(10, '판타지', '초현실 세계관 중심', 10),
(11, '다큐멘터리', '실제 사건과 인물 기록', 11),
(12, '애니메이션', '애니메이션 기반 영상', 12),
(13, '실험/예술', '비정형 아트필름', 13),
(14, '음악/공연', '음악과 공연 중심', 14),
(15, '가족/아동', '가족 관람과 아동 대상', 15),
(16, '청춘/학원', '성장과 학교 중심', 16),
(17, '역사/시대극', '역사와 시대 배경', 17),
(18, '스포츠', '스포츠 경기와 선수 서사', 18),
(19, '기타', '기타 장르', 19);
